apiVersion: v1
kind: Service
metadata:
  name: tripviewer
spec:
  selector:
    app: tripviewer
  ports:
    - port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripviewer
spec:
  selector:
    matchLabels:
      app: tripviewer
  template:
    metadata:
      labels:
        app: tripviewer
    spec:
      containers:
        - name: tripviewer
          image: wabrezohcontainerregistry.azurecr.io/tripviewer
          env:
            - name: SQL_SERVER
              value: wabrez-openhack-sql.database.windows.net
            - name: SQL_DBNAME
              value: myDrivingDB
            - name: SQL_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: db-username
            - name: SQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: db-password
            - name: TRIPS_API_ENDPOINT
              value: http://trips
            - name: USER_API_ENDPOINT
              value: http://userprofile
            - name: BING_MAPS_KEY
              value: "AiVZurOu5-zAjFCsq4_hzsHilRAnQ2rMyLhfJKSTqN4tweyhs53iguG7MtgwZ1kg"
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
